import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:shared_preferences/shared_preferences.dart';

import 'bundle.dart';
import 'metadata_service.dart';

/// Seeds the TMDB metadata cache and poster files for the built-in
/// catalog from bundled assets (assets/seed_metadata/, regenerated by
/// tool/harvest_seed_metadata.dart — see docs/SEED-CATALOG.md), so a
/// fresh keyless install shows artwork, descriptions, and episode names
/// for every seeded title. Same gap-fill semantics as a bundle import:
/// existing cache rows and poster files always win, so a user's own
/// TMDB matches are never overwritten. Best-effort and idempotent; a
/// one-time flag skips the work on later launches.

/// Bump when the bundled metadata is regenerated for a changed catalog
/// so existing installs pick up the new titles' rows (gap-fill keeps
/// their own rows untouched).
const kSeedMetadataFlag = 'seed_metadata_v1';

const kSeedMetadataAsset = 'assets/seed_metadata/metadata.json';

/// Asset path of a bundled poster/still file referenced by a seed row.
String seedPosterAsset(String file) => 'assets/seed_metadata/posters/$file';

/// Parse the bundled metadata.json into lookupKey → row, with the same
/// validation the bundle importer applies (non-empty string key; row
/// field types are checked at insert time, a bad row skips).
Map<String, Map<String, dynamic>> parseSeedMetadataRows(String json) {
  final rows = <String, Map<String, dynamic>>{};
  final decoded = jsonDecode(json);
  final entries = (decoded as Map<String, dynamic>)['entries'];
  for (final raw in entries as List<dynamic>) {
    final row = raw as Map<String, dynamic>;
    final key = row['lookupKey'];
    if (key is String && key.isNotEmpty) rows[key] = row;
  }
  return rows;
}

Future<void> seedBundledMetadata({
  Future<Directory> Function()? postersDirProvider,
  Future<String> Function(String asset)? loadString,
  Future<Uint8List> Function(String asset)? loadBytes,
}) async {
  try {
    final prefs = await SharedPreferences.getInstance();
    if (prefs.getBool(kSeedMetadataFlag) ?? false) return;

    final rows = parseSeedMetadataRows(await (loadString ??
        rootBundle.loadString)(kSeedMetadataAsset));
    final fileNames = <String>{
      for (final row in rows.values)
        for (final field in ['posterFile', 'stillFile', 'showPosterFile'])
          if (row[field] is String) row[field] as String,
    };
    final posters = <String, Uint8List>{};
    for (final name in fileNames) {
      try {
        posters[name] = loadBytes != null
            ? await loadBytes(seedPosterAsset(name))
            : (await rootBundle.load(seedPosterAsset(name)))
                .buffer
                .asUint8List();
      } catch (_) {
        // A missing image asset costs that artwork, not the seed.
      }
    }
    await seedMetadataGapFill(rows, posters,
        postersDirProvider: postersDirProvider);
    await prefs.setBool(kSeedMetadataFlag, true);
    // Screens may have already resolved these keys to the fallback this
    // session — drop the in-memory answers so the seeded rows show.
    MetadataService.instance.notifyExternalSeed();
  } catch (e) {
    // Best-effort: entries fall back to parsed-name metadata (and live
    // TMDB if the user has a key); retried next launch (flag not set).
    debugPrint('metadata seed failed: $e');
  }
}
